version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    networks:
      - my_network
      
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    command: npm start  
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network
  
  voz_order_script:
    build:
      context: ./voz
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001" 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

